---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  namespace: ns-hwakabh
spec:
  #replicas: 2
  replicas: 4
  selector:
    matchLabels:
      name: dev-hwakabh
  template:
    metadata:
      labels:
        name: dev-hwakabh
    spec:
      containers:
      - image: busybox:latest
        name: my-busybox
        command: ["sh", "-c", "echo busybox-1 running && sleep 60"]
