---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrole-ro-endpoints
rules:
- apiGroups: [""]
  resources:
  - "services"
  - "endpoints"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
