---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rs-testings
  namespace: ns-hwakabh
spec:
  hard:
    requests.cpu: 1
    requests.memory: 1G
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: lmt-testings
  namespace: ns-hwakabh
spec:
  hard:
    limits.cpu: 2
    limits.memory: 2G
