---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rs-testings
spec:
  hard:
    requests.cpu: 1
    requests.memory: 1G
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: lmt-testings
spec:
  hard:
    limits.cpu: 2
    limits.memory: 2G

# kubectl run nginx --restart=Never --image=nginx --requests='cpu=100m,memory=256Mi' --limits='cpu=200m,memory=512Mi'
# kubectl get quota
# kubectl get quota/rs-testings -o yaml