# ---
# Before apply manifest: need to create ServiceAccount, named hwkabh
# kubectl create sa hwakabh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/logs"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-hwakabh-reader
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
# If binding to SA, apiGroup should be blank string
- apiGroup: ""
  kind: ServiceAccount
  name: hwakabh
  namespace: default

