---
apiVersion: v1
kind: Secret
data:
  username: cG9zdGdyZXMK
  password: cG9zdGdyZXMK
metadata:
  name: secret-postgres
---
apiVersion: v1
kind: Secret
stringData:
  # Same as `kubectl create secret generic secret-mysql --from-literal username=root --from-literal password=password`
  username: root
  password: password
metadata:
  name: secret-mysql


# Before apply manifests:
#   echo -e 'cG9zdGdyZXMK' |base64 -D #-> `postgres`
# kubectl get secrets
# kubectl get secret/secret-postgres -o yaml
# kubectl describe secret/secret-postgres
