---
apiVersion: v1
kind: Pod
metadata:
  name: multicontainers-pod
spec:
  containers:
  - name: busybox1
    image: busybox:latest
    command:
      - /bin/sh
      - -c
      - 'echo busybox1 ; sleep 600'
  - name: busybox2
    image: busybox:latest
    command:
      - /bin/sh
      - -c
      - 'echo busybox2; sleep 600'

# kubectl logs pod/multicontainers-pod -c busybox1
# kubectl logs pod/multicontainers-pod -c busybox2
