---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: testpv01
  labels:
    volume: test_pvs
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    server: gke-nfs-server
    path: "/home/hwakabh/nfs"
