---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
  - name: myvolume
    hostPath:
      path: /tmp/foo
      type: DirectoryOrCreate
  containers:
  - name: busybox
    image: busybox:latest
    command:
      - /bin/sh
      - -c
      - 'sleep 600'
    volumeMounts:
    - mountPath: /foo
      name: myvolume


# kubectl exec -it busybox -- /bin/sh -c 'df -h'
# kubectl get pods -o wide
# gcloud compute ssh NODE_NAME_PODS_RUNNING
#   ls -al /tmp
# kubectl delete pod/busybox [--grace-period=0 --force]
# gcloud compute ssh NODE_NAME_PODS_RUNNING
#   ls -al /tmp
