---
apiVersion: v1
kind: Secret
type: Opaque
data:
  mariadb_pass: cGFzc3dvcmQ= #-> password
metadata:
  name: mariacreds
---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb
spec:
  containers:
  - name: mariadb
    image: mariadb:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mariacreds
          key: mariadb_pass

# kubectl get pod/mariadb -o yaml
# kubectl exec -it mariadb -- /bin/bash -c 'echo $MYSQL_ROOT_PASSWORD'
# kubectl exec -it mariadb -- /bin/bash
#   mysql -u root -p
#   \dt
#   \q
# exit
