---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
  - name: myvolume
    emptyDir: {}
  containers:
  - image: busybox:latest
    name: busybox
    command:
      - /bin/sh
      - -c
      - 'sleep 600'
    volumeMounts:
    - mountPath: /vol
      name: myvolume

# kubectl exec -it busybox -- /bin/sh -c 'df -h'
