---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command:
      - printf
    args:
      - 'Hello World\n'
  restartPolicy: Never