apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command:
      - /bin/sh
      - -c
      - 'sleep 600'
    workingDir: /tmp

# kubectl get pods
# kubectl describe pod/busybox
# kubectl exec -it busybox -- /bin/sh -c pwd