---
apiVersion: v1
data:
  password: some_database_password
  username: admin
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dbcred
---
apiVersion: v1
kind: Pod
metadata:
  name: envar-demo-pod
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    envFrom:
      # Just provides name of ConfigMap, then load all the Key-Values in Pods
    - configMapRef:
        name: dbcred

# kubectl exec -it envar-demo-pod env |egrep "username|password"
