---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: testpv01
  labels:
    volume: testpvs
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    server: localhost
    path: "/root/nfs/"
