---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testpvc01
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  selector:
    matchLabels:
      volume: test_pvs
