---
apiVersion: v1
kind: Secret
data:
  mydbpass: c29tZV9kYXRhYmFzZV9wYXNzd29yZA==
metadata:
  name: dbcreds
  namespace: ns-hwakabh
---
apiVersion: v1
kind: Secret
data:
  db_user: cm9vdA==
  db_pass: cGFzc3dvcmQ=
metadata:
  name: dbcreds3
  namespace: default

# kubectl apply -f secret.yaml
# kubectl get secret dbcreds -o yaml
#   #Check plaintext is `some_database_password`
#   echo -n 'c29tZV9kYXRhYmFzZV9wYXNzd29yZA==' |base64 -D
# kubectl get secret dbcreds3 -o yaml
#   #Check plaintext is `root`
#   echo -n 'cm9vdA==' |base64 -D
#   #Check plaintext is `password`
#   echo -n 'cGFzc3dvcmQ=' |base64 -D
