---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd

# kubectl get pods,ds
# kubectl get pods -o wide
#   ---> All pods created by DaemonSet would be allocated on each worker-node separatedly.
# kubectl delete ds/fluentd
# kubectl get pods
