apiVersion: v1
kind: Pod
metadata:
  name: basic-three-tier-apps
  namespace: ns-hwakabh
spec:
  containers:
  - name: web-001
    image: nginx:alpine
    command: ["sleep", "6000"]
  - name: db-001
    image: postgres
    command: ["sleep", "6000"]
  - name: app-001
    image: python
    command: ["sleep", "6000"]
