apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployments
spec:
  replicas: 2
  selector:
    matchLabels:
      component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
      - image: nginx
        name: hwakabh-nginx
