apiVersion: v1
kind: Pod
metadata:
  name: my-alpine
  namespace: ns-hwakabh
  labels:
    component: alpine
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["sleep", "6000"]
