apiVersion: v1
kind: Pod
metadata:
  name: my-pod-dev
  namespace: ns-hwakabh
spec:
  containers:
  - name: web-001
    image: nginx:alpine
    env:
    - name: NAME_1
      value: Alice
    args: ["sleep", "6000"]
    workingDir: /tmp
  - name: web-002
    image: nginx:alpine
    env:
    - name: NAME_2
      value: Bob
    args: ["sleep", "6000"]

# Check environment variables in containers with:
# kubectl -n ns-hwakabh exec -it my-pod-dev -c web-001 /bin/sh
# pwd ; echo $NAME_1
# kubectl -n ns-hwakabh exec -it my-pod-dev -c web-002 /bin/sh
# pwd ; echo $NAME_2
