apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rc
  namespace: ns-hwakabh
spec:
  replicas: 2
  selector:
    matchLabels:
      name: dev-hwakabh
  template:
    metadata:
      labels:
        name: dev-hwakabh
    spec:
      containers:
      - image: nginx
        name: nginx-rc-1
        command: ["sh", "-c", "sleep 6000"]
      - image: nginx
        name: nginx-rc-2
