---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-hostpath
spec:
  containers:
  - name: c1
    image: busybox
    command: ["/bin/sh", "-c", "sleep 6000"]
    volumeMounts:
    - mountPath: /foo
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /root/bar
      type: DirectoryOrCreate
