apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx2
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    livenessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 10
      exec:
        command: ["ls"]
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
