---
apiVersion: v1
kind: Pod
metadata:
  name: nginx01
spec:
  containers:
  - image: nginx
    name: nginx
  nodeSelector:
    node: primary-node
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx02
spec:
  containers:
  - image: nginx
    name: nginx
  nodeSelector:
    node: primary-node
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx03
spec:
  containers:
  - image: nginx
    name: nginx
  nodeSelector:
    node: primary-node
