---
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
spec:
  containers:
  - image: nginx
    name: nginx
  nodeSelector:
    node: primary-node
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  containers:
  - image: nginx
    name: nginx
  nodeSelector:
    node: primary-node
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx3
spec:
  containers:
  - image: nginx
    name: nginx
  nodeSelector:
    node: secondary-node

# Before applying manifest, labeling to nodes with kubectl, since manifests for node might cause unschedulable cluster
#   kubectl label node/FIRST_NODE_NAME node=primary-node
#   kubectl label node/SECOND_NODE_NAME node=secondary-node
#   kubectl label node/THIRD_NODE_NAME node=third-node
#   kubectl get nodes -L node
# After applying manifest with kubectl: 
#   kubectl get pods -o wide
# Cleanup labels with:
#   kubectl label node --all node-
