---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest

# kubectl get pods
# kubectl describe pod/nginx
# kubectl get pod/nginx -o yaml
# kubectl delete pod/nginx [--grace-period=0 --force]