---
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    app: v1
spec:
  containers:
  - name: nginx
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app: v2
spec:
  containers:
  - name: nginx
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx3
  labels:
    app: v1
spec:
  containers:
  - name: nginx
    image: nginx:latest

# kubectl get pods
# kubectl get pods --show-labels
# kubectl get pods -L app
# kubectl get pods -l app=v1
# kubectl delete pod/nginx{1..3} [--grace-period=0 --force]