---
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  namespace: ns-hwakabh
  labels:
    app: v1
spec:
  containers:
  - name: nginx1
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  namespace: ns-hwakabh
  labels:
    app: v2
spec:
  containers:
  - name: nginx2
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx3
  namespace: ns-hwakabh
  labels:
    app: v1
spec:
  containers:
  - name: nginx3
    image: nginx:latest
