---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myuser
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
  serviceAccountName: myuser

# kubectl get pods,sa,secrets
# kubectl get sa/myuser -o yaml
# kubectl get secret/myuser-token-XXXX -o yaml
