---
apiVersion: v1
kind: ConfigMap
data:
  # --from-file style
  STRING: |
    ping
    pong
metadata:
  name: cm-contents
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    command:
      - /bin/sh
      - -c
      - 'sleep 600'
    envFrom:
    - configMapRef:
        name: cm-contents

# kubectl exec -it nginx -- /bin/sh -c 'echo $STRING'
