---
apiVersion: v1
kind: Secret
type: Opaque
data:
  db_user: cm9vdA== #-> root
  db_pass: cGFzc3dvcmQ= #-> password
metadata:
  name: dbcreds
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: dbcreds

# kubectl get pod,secret -o wide
# kubectl exec -it nginx -- /bin/bash -c env |grep db_
