---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command:
      - /bin/sh
      - -c
      - 'sleep 600'
    livenessProbe:
      initialDelaySeconds: 60
      exec:
        command:
          - /bin/sh
          - -c
          - 'ping -c 20 localhost'

# kubectl get pods
# kubectl describe pod/busybox
