---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deploy
  namespace: ns-hwakabh
  labels:
    component: busybox
spec:
  replicas: 2
  selector:
    matchLabels:
      component: busybox
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        component: busybox
    spec:
      containers:
      - name: my-container
        image: busybox:latest
        command: ['/bin/sh', '-c', 'sleep 600']
---
apiVersion: v1
kind: Service
metadata:
  name: my-cluster-ip-svc
  namespace: ns-hwakabh
spec:
  type: ClusterIP
  selector:
    component: busybox
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 80

