---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: ns-hwakabh
  labels:
    component: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      component: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
      - name: my-container
        image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: my-cluster-ip-svc
  namespace: ns-hwakabh
spec:
  type: ClusterIP
  selector:
    component: nginx
  ports:
  - protocol: TCP
    name: http
    port: 8088      #-> Exposed ClusterIP's port
    targetPort: 80  #-> Pod Awaiting port

#-> `gcloud compute ssh` to worker-node running nginx
#-> `docker run --rm -it alpine:latest /bin/sh` to create client container
#-> `wget -O - CLUSTER_IP_ADDRESS:8088` to check access
