---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: ns-hwakabh
  labels:
    component: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      component: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        command: ['/bin/sh', '-c', 'sleep 600']
---
apiVersion: v1
kind: Service
metadata:
  name: my-cluster-ip-svc
  namespace: ns-hwakabh
spec:
  type: ClusterIP
  selector:
    component: nginx
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 80

