---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ns-hwakabh
  labels:
    component: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      component: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
      - name: my-app-container
        image: nginx:1.24
        command: ['/bin/sh', '-c', 'echo App Running && sleep 600']

---
apiVersion: v1
kind: Service
metadata:
  name: my-node-port
  namespace: ns-hwakabh
spec:
  type: NodePort
  selector:
    component: nginx
  ports:
  - port: 80

