---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-2
  namespace: ns-hwakabh
  labels:
    component: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      component: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
      - name: my-app-container
        image: nginx:latest

---
apiVersion: v1
kind: Service
metadata:
  name: my-node-port
  namespace: ns-hwakabh
spec:
  type: NodePort
  selector:
    component: nginx
  ports:
  - protocol: TCP
    name: http
    port: 8088      #-> Exposed NodePort number
    targetPort: 80  #-> Awaiting container port number

#-> `gcloud compute ssh` to NOT running nginx containers, also confirm with `docker ps |grep nginx`
#-> Externally from the Pods, `curl -X GET CLUSTER_IP:8088` to get access

